services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\EcontBundle\:
        resource: '../../../src/{Command,Client}'

    Answear\EcontBundle\ConfigProvider: ~

